# @format

version: "3.8"

services:
  finance-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgres://vypham:vyPham%40%40%40%40%40123@postgre:5432/finance
    networks:
      - my_shared_network
    restart: unless-stopped
networks:
  my_shared_network:
    external: true
